-- ############################# At Least Once Checked out Books ##########################################################

-- At least once checked out Books  (Yashpal-DB = 20866)
SELECT items.barcode, biblioitems.isbn, items.biblionumber, biblio.title, biblio.author,items.dateaccessioned FROM items LEFT JOIN issues  ON  (items.itemnumber = issues.itemnumber)LEFT JOIN old_issues  ON  (items.itemnumber = old_issues.itemnumber)LEFT JOIN biblio      ON  (items.biblionumber = biblio.biblionumber)LEFT JOIN biblioitems ON  (items.biblionumber = biblioitems.biblionumber)WHERE items.itype = 'BK'AND   items.homebranch = 'DL'AND   (issues.itemnumber IS NOT NULL OR old_issues.itemnumber IS NOT NULL)GROUP BY items.itemnumber ORDER BY items.dateaccessioned DESC;

-- At least once checked out Books excluding notforloan, withdrawn, damaged and lost  (Yashpal-DB = 19069)
SELECT items.barcode, biblioitems.isbn, items.biblionumber, biblio.title, biblio.author,items.dateaccessioned FROM items LEFT JOIN issues  ON  (items.itemnumber = issues.itemnumber)LEFT JOIN old_issues  ON  (items.itemnumber = old_issues.itemnumber)LEFT JOIN biblio      ON  (items.biblionumber = biblio.biblionumber)LEFT JOIN biblioitems ON  (items.biblionumber = biblioitems.biblionumber)WHERE items.itype = 'BK'AND   items.homebranch = 'DL'AND   items.notforloan = 0   AND   items.wthdrawn = 0     AND   items.damaged = 0      AND   items.itemlost = 0   AND   (issues.itemnumber IS NOT NULL OR old_issues.itemnumber IS NOT NULL) GROUP BY items.itemnumber ORDER BY items.dateaccessioned DESC;

-- Not For Loan (Yashpal-DB = 45)
SELECT items.barcode, biblioitems.isbn, items.biblionumber, biblio.title, biblio.author,items.dateaccessioned FROM items LEFT JOIN issues  ON  (items.itemnumber = issues.itemnumber)LEFT JOIN old_issues  ON  (items.itemnumber = old_issues.itemnumber)LEFT JOIN biblio      ON  (items.biblionumber = biblio.biblionumber)LEFT JOIN biblioitems ON  (items.biblionumber = biblioitems.biblionumber)WHERE items.itype = 'BK'AND   items.homebranch = 'DL'AND   items.notforloan != 0  AND   items.wthdrawn = 0     AND   items.damaged = 0      AND   items.itemlost = 0     AND   (issues.itemnumber IS NOT NULL OR old_issues.itemnumber IS NOT NULL)GROUP BY items.itemnumber ORDER BY items.dateaccessioned DESC;

-- Withdrawn Books (Yashpal-DB = 1702)
SELECT items.barcode, biblioitems.isbn, items.biblionumber, biblio.title, biblio.author,items.dateaccessioned FROM items LEFT JOIN issues  ON  (items.itemnumber = issues.itemnumber)LEFT JOIN old_issues  ON  (items.itemnumber = old_issues.itemnumber)LEFT JOIN biblio      ON  (items.biblionumber = biblio.biblionumber)LEFT JOIN biblioitems ON  (items.biblionumber = biblioitems.biblionumber)WHERE items.itype = 'BK'AND   items.homebranch = 'DL'AND   items.notforloan = 0    AND   items.wthdrawn != 0     AND   items.damaged = 0       AND   items.itemlost = 0      AND   (issues.itemnumber IS NOT NULL OR old_issues.itemnumber IS NOT NULL)GROUP BY items.itemnumber ORDER BY items.dateaccessioned DESC;

-- Damaged Books (Yashpal-DB = 2)
SELECT items.barcode, biblioitems.isbn, items.biblionumber, biblio.title, biblio.author,items.dateaccessioned FROM items LEFT JOIN issues  ON  (items.itemnumber = issues.itemnumber)LEFT JOIN old_issues  ON  (items.itemnumber = old_issues.itemnumber)LEFT JOIN biblio      ON  (items.biblionumber = biblio.biblionumber)LEFT JOIN biblioitems ON  (items.biblionumber = biblioitems.biblionumber)WHERE items.itype = 'BK'AND   items.homebranch = 'DL'AND   items.notforloan = 0    AND   items.wthdrawn = 0      AND   items.damaged != 0      AND   items.itemlost = 0      AND   (issues.itemnumber IS NOT NULL OR old_issues.itemnumber IS NOT NULL)GROUP BY items.itemnumber ORDER BY items.dateaccessioned DESC;

-- Lost Books (Yashpal-DB = 46)
SELECT items.barcode, biblioitems.isbn, items.biblionumber, biblio.title, biblio.author,items.dateaccessioned FROM items LEFT JOIN issues  ON  (items.itemnumber = issues.itemnumber)LEFT JOIN old_issues  ON  (items.itemnumber = old_issues.itemnumber)LEFT JOIN biblio      ON  (items.biblionumber = biblio.biblionumber)LEFT JOIN biblioitems ON  (items.biblionumber = biblioitems.biblionumber)WHERE items.itype = 'BK'AND   items.homebranch = 'DL'AND   items.notforloan = 0    AND   items.wthdrawn = 0      AND   items.damaged = 0       AND   items.itemlost != 0     AND   (issues.itemnumber IS NOT NULL OR old_issues.itemnumber IS NOT NULL)GROUP BY items.itemnumber ORDER BY items.dateaccessioned DESC;

-- Lost and withdrawn Books (Yashpal-DB = 1)
SELECT items.barcode, biblioitems.isbn, items.biblionumber, biblio.title, biblio.author,items.dateaccessioned FROM items LEFT JOIN issues  ON  (items.itemnumber = issues.itemnumber)LEFT JOIN old_issues  ON  (items.itemnumber = old_issues.itemnumber)LEFT JOIN biblio      ON  (items.biblionumber = biblio.biblionumber)LEFT JOIN biblioitems ON  (items.biblionumber = biblioitems.biblionumber)WHERE items.itype = 'BK'AND   items.homebranch = 'DL'AND   items.notforloan = 0    AND   items.wthdrawn != 0     AND   items.damaged = 0       AND   items.itemlost != 0     AND    (issues.itemnumber IS NOT NULL OR old_issues.itemnumber IS NOT NULL)GROUP BY items.itemnumber ORDER BY items.dateaccessioned DESC;



-- ############################# Never Checked out Books ##########################################################

-- Never checked out Books  (Yashpal-DB = 5474)  
SELECT items.barcode, biblioitems.isbn, items.biblionumber,  biblio.title, biblio.author,items.dateaccessioned FROM items  LEFT JOIN issues      ON  (items.itemnumber = issues.itemnumber) LEFT JOIN old_issues  ON  (items.itemnumber = old_issues.itemnumber) LEFT JOIN biblio      ON  (items.biblionumber = biblio.biblionumber) LEFT JOIN biblioitems ON  (items.biblionumber = biblioitems.biblionumber) WHERE items.itype = 'BK' AND   items.homebranch = 'DL' AND   (issues.itemnumber IS NULL AND old_issues.itemnumber IS NULL) GROUP BY items.itemnumber  ORDER BY items.dateaccessioned DESC;   

-- Never checked out Books excluding notforloan, withdrawn, damaged and lost  (Yashpal-DB = 3219) 
SELECT items.barcode, biblioitems.isbn, items.biblionumber,  biblio.title, biblio.author,items.dateaccessioned FROM items  LEFT JOIN issues      ON  (items.itemnumber = issues.itemnumber) LEFT JOIN old_issues  ON  (items.itemnumber = old_issues.itemnumber) LEFT JOIN biblio      ON  (items.biblionumber = biblio.biblionumber) LEFT JOIN biblioitems ON  (items.biblionumber = biblioitems.biblionumber) WHERE items.itype = 'BK' AND   items.homebranch = 'DL' AND   items.notforloan = 0   AND   items.wthdrawn = 0      AND   items.damaged = 0       AND   items.itemlost = 0      AND   (issues.itemnumber IS NULL AND old_issues.itemnumber IS NULL) GROUP BY items.itemnumber  ORDER BY items.dateaccessioned DESC;  

-- Not For Loan (Yashpal-DB = 19) 
SELECT items.barcode, biblioitems.isbn, items.biblionumber,  biblio.title, biblio.author,items.dateaccessioned FROM items  LEFT JOIN issues      ON  (items.itemnumber = issues.itemnumber) LEFT JOIN old_issues  ON  (items.itemnumber = old_issues.itemnumber) LEFT JOIN biblio      ON  (items.biblionumber = biblio.biblionumber) LEFT JOIN biblioitems ON  (items.biblionumber = biblioitems.biblionumber) WHERE items.itype = 'BK' AND   items.homebranch = 'DL' AND   items.notforloan != 0   AND   items.wthdrawn = 0      AND   items.damaged = 0       AND   items.itemlost = 0      AND   (issues.itemnumber IS NULL AND old_issues.itemnumber IS NULL) GROUP BY items.itemnumber  ORDER BY items.dateaccessioned DESC;  

-- Withdrawn Books (Yashpal-DB = 1359) 
SELECT items.barcode, biblioitems.isbn, items.biblionumber,  biblio.title, biblio.author,items.dateaccessioned FROM items  LEFT JOIN issues      ON  (items.itemnumber = issues.itemnumber) LEFT JOIN old_issues  ON  (items.itemnumber = old_issues.itemnumber) LEFT JOIN biblio      ON  (items.biblionumber = biblio.biblionumber) LEFT JOIN biblioitems ON  (items.biblionumber = biblioitems.biblionumber) WHERE items.itype = 'BK' AND   items.homebranch = 'DL' AND   items.notforloan = 0     AND   items.wthdrawn != 0      AND   items.damaged = 0        AND   items.itemlost = 0       AND   (issues.itemnumber IS NULL AND old_issues.itemnumber IS NULL) GROUP BY items.itemnumber  ORDER BY items.dateaccessioned DESC;  

-- Damaged Books (Yashpal-DB = 8) 
SELECT items.barcode, biblioitems.isbn, items.biblionumber,  biblio.title, biblio.author,items.dateaccessioned FROM items  LEFT JOIN issues      ON  (items.itemnumber = issues.itemnumber) LEFT JOIN old_issues  ON  (items.itemnumber = old_issues.itemnumber) LEFT JOIN biblio      ON  (items.biblionumber = biblio.biblionumber) LEFT JOIN biblioitems ON  (items.biblionumber = biblioitems.biblionumber) WHERE items.itype = 'BK' AND   items.homebranch = 'DL' AND   items.notforloan = 0     AND   items.wthdrawn = 0       AND   items.damaged != 0       AND   items.itemlost = 0       AND   (issues.itemnumber IS NULL AND old_issues.itemnumber IS NULL) GROUP BY items.itemnumber  ORDER BY items.dateaccessioned DESC;  

-- Lost Books (Yashpal-DB = 860) 
SELECT items.barcode, biblioitems.isbn, items.biblionumber,  biblio.title, biblio.author,items.dateaccessioned FROM items  LEFT JOIN issues      ON  (items.itemnumber = issues.itemnumber) LEFT JOIN old_issues  ON  (items.itemnumber = old_issues.itemnumber) LEFT JOIN biblio      ON  (items.biblionumber = biblio.biblionumber) LEFT JOIN biblioitems ON  (items.biblionumber = biblioitems.biblionumber) WHERE items.itype = 'BK' AND   items.homebranch = 'DL' AND   items.notforloan = 0     AND   items.wthdrawn = 0       AND   items.damaged = 0        AND   items.itemlost != 0      AND   (issues.itemnumber IS NULL AND old_issues.itemnumber IS NULL) GROUP BY items.itemnumber  ORDER BY items.dateaccessioned DESC;  

-- Lost and withdrawn Books (Yashpal-DB = 9) 
SELECT items.barcode, biblioitems.isbn, items.biblionumber,  biblio.title, biblio.author,items.dateaccessioned FROM items  LEFT JOIN issues      ON  (items.itemnumber = issues.itemnumber) LEFT JOIN old_issues  ON  (items.itemnumber = old_issues.itemnumber) LEFT JOIN biblio      ON  (items.biblionumber = biblio.biblionumber) LEFT JOIN biblioitems ON  (items.biblionumber = biblioitems.biblionumber) WHERE items.itype = 'BK' AND   items.homebranch = 'DL' AND   items.notforloan = 0     AND   items.wthdrawn != 0      AND   items.damaged = 0        AND   items.itemlost != 0      AND   (issues.itemnumber IS NULL AND old_issues.itemnumber IS NULL) GROUP BY items.itemnumber  ORDER BY items.dateaccessioned DESC;


