package es.oeuvr.domain;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UploadLog generated by hbm2java
 */
@Entity
@Table(name = "Upload_Log", catalog = UploadLog.OEUVRES)
public class UploadLog implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	static final String OEUVRES = "oeuvres";
	private Long id;
	private String filename;
	private String failed;
	private String comments;
	private Integer uploadDate;

	public UploadLog() {
	}

	public UploadLog(String filename, String failed, String comments,
			Integer uploadDate) {
		this.filename = filename;
		this.failed = failed;
		this.comments = comments;
		this.uploadDate = uploadDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "filename", length = 256)
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Column(name = "Failed", length = 65535)
	public String getFailed() {
		return this.failed;
	}

	public void setFailed(String failed) {
		this.failed = failed;
	}

	@Column(name = "Comments", length = 256)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "upload_date")
	public Integer getUploadDate() {
		return this.uploadDate;
	}

	public void setUploadDate(Integer uploadDate) {
		this.uploadDate = uploadDate;
	}

}
